[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "claudetest"
version = "0.1.0"
description = "A simple Python application"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
claudetest = "claudetest.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]